name: efood_multivendor_driver
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.10
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  http: ^0.13.4
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.1.0+1
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.6
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  image_picker: ^0.8.5+3
  disable_battery_optimization: ^1.1.0+1
  phone_number: ^1.0.0
  country_code_picker: ^2.0.2
#  location: ^4.4.0
  audioplayers: ^0.20.1
  flutter_widget_from_html_core: ^0.9.1
  fwfh_text_style: ^2.22.8+1
  modal_bottom_sheet: ^2.1.2

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900